//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace card_against_humanity_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("card_against_humanity_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BackStart {
            get {
                object obj = ResourceManager.GetObject("BackStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the church Here is the steeple Open the doors And there is ____.
        ///50% of all marriages end in ____.
        ///As the mom of five rambunctious boys, I&apos;m no stranger to ____.
        ///Next from J.K. Rowling: Harry Potter and the Chamber of ____.
        ///This is the way the world ends This is the way the world ends Not with a bang but with ____.
        ///After four platinum albums and three Grammys, it&apos;s time to get back to my roots, to what inspired me to make music in the first place: ____.
        ///When Pharaoh remained unmoved, Moses cal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackSen {
            get {
                return ResourceManager.GetString("BlackSen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charles {
            get {
                object obj = ResourceManager.GetObject("Charles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Josephus {
            get {
                object obj = ResourceManager.GetObject("Josephus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kurt {
            get {
                object obj = ResourceManager.GetObject("Kurt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meme1 {
            get {
                object obj = ResourceManager.GetObject("meme1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meme2 {
            get {
                object obj = ResourceManager.GetObject("meme2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meme3 {
            get {
                object obj = ResourceManager.GetObject("meme3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throwing grapes at a man until he loses touch with reality.
        ///My Uber driver, Pavel.
        ///The Hamburglar.
        ///A stray pube.
        ///privilege.
        ///Facebook.
        ///Pac-Man uncontrollably guzzling cum.
        ///Forced sterilization.
        ///An Oedipus complex.
        ///Scientology.
        ///My fat daughter.
        ///Active listening.
        ///Vigorous jazz hands.
        ///An M. Night Shyamalan plot twist.
        ///The rhythms of Africa.
        ///The homosexual agenda.
        ///Having big dreams but no realistic way to achieve them.
        ///A time travel paradox.
        ///Lactation.
        ///Dick fingers.
        ///Dying.
        ///My good bra.
        ///Me t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteSen {
            get {
                return ResourceManager.GetString("WhiteSen", resourceCulture);
            }
        }
    }
}
